title: Divya Shanmugam
url: "https://dmshanmugam.github.io"
baseurl: "/researcher/"

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_url: ""
footer_text: "~~~"

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "/researcher/pdfs/cv.pdf"
 - name: "Blog"
   link: "blog"
